### ISSUE TITLE
pyez_rpc task plugin: How to return text format instead of XML?

### ISSUE THREAD

**Issue by suhaibasaeed** [DataKnox/nornir_pyez#37]
I am trying to execute the pyez_rpc task plugin and have it return text instead of XML by passing in the 'format' option via the extras dictionary but seem to be hitting the below error:

My code looks like this

```
def get_bgp_summary_data(task):

    result_text = task.run(task=pyez_rpc, func="get-bgp-summary-information", extras= {"format" : "text"})
    task.host["bgp_summary_text"] = result_text[0].result
```

```
ERROR    nornir.core.task:task.py:115 Host 'xxx.xxx': task 'pyez_rpc' failed with traceback:
Traceback (most recent call last):
  File "/home/gammatelecom.com/ssaeed/scripts/nornir_env/lib/python3.8/site-packages/jnpr/junos/device.py", line 834, in execute
    rpc_rsp_e = self._rpc_reply(
  File "/home/gammatelecom.com/ssaeed/scripts/nornir_env/lib/python3.8/site-packages/jnpr/junos/decorators.py", line 165, in wrapper
    raise ex
  File "/home/gammatelecom.com/ssaeed/scripts/nornir_env/lib/python3.8/site-packages/jnpr/junos/decorators.py", line 117, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/home/gammatelecom.com/ssaeed/scripts/nornir_env/lib/python3.8/site-packages/jnpr/junos/device.py", line 1457, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e, filter_xml)._NCElement__doc
  File "/home/gammatelecom.com/ssaeed/scripts/nornir_env/lib/python3.8/site-packages/ncclient/manager.py", line 246, in execute
    return cls(self._session,
  File "/home/gammatelecom.com/ssaeed/scripts/nornir_env/lib/python3.8/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 52, in request
    return self._request(rpc)
  File "/home/gammatelecom.com/ssaeed/scripts/nornir_env/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 373, in _request
    raise RPCError(to_ele(self._reply._raw), errs=errors)
ncclient.operations.rpc.RPCError: error: syntax error, expecting <invoke-on>
error: syntax error, expecting <filter type="subtree"> or <filter type="subtree" />
```

TIA

**Comment by suhaibasaeed** [comment]
I've found the workaround for this. My original code about used the `format:text` option which is only valid with the `get-config` RPC.

The below code did what I needed via the `.cli()` method but I had to use a custom task and do a direct connection to pyez
```
def get_bgp_summary_data(task):
    pyez_direct = task.host.get_connection("pyez", task.nornir.config)
    text_output = pyez_direct.cli(command='show bgp summary')

    task.host["bgp_summary_text"] = text_output
```
